# Generated by Django 2.0.6 on 2018-11-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='深圳', max_length=100, verbose_name='地址'),
        ),
    ]
